### ISSUE TITLE
Issue with creating new proposal

### ISSUE THREAD

**Issue by Cybnate** [Daology/Support#14]
URL: http://daology.org/u/cybnate/proposals/new/Nu/NuBits/proposal 

 USER AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0

please detail your issue below
On creating as proposal the window to enter the body of the proposal is not available. The title and proposal status are there. 
Hope this is not the end of Daology, but just a bug!
Restarted my browser just to be sure it is not on my end.
Example proposal: https://daology.org/u/cybnate/proposals/2457433f971e5b0a55e5a165ad01a101d198722c

**Comment by CoinGame** [comment]
Hi Cybnate. Thanks for using the bug button. I'm unable to reproduce this. If you hit F12 and look in the javascript console do you see any errors? We haven't made any changes to the site recently. I've tried on several different browsers one two different platforms. Do you have any sort of brower plugins that could be interfering as well?

**Comment by Cybnate** [comment]
Only a video code H264 and Citrix Receiver are active as plugins. 
Nothing I can see with F12, but I'm not a web developer.
Just tested with Windows and Firefox and no problem. Will use that VM for now to post my proposals.
Please let me know if I need to post something which may be useful for you.

**Comment by Cybnate** [comment]
Only a video code H264 and Citrix Receiver are active as plugins. 
Nothing I can see with F12, but I'm not a web developer.
Just tested with Windows and Firefox and no problem. Will use that VM for now to post my proposals.
Please let me know if I need to post something which may be useful for you.

**Comment by Cybnate** [comment]
This problem appears to be have solved itself.
