### ISSUE TITLE
Closed testing sign-up sheet

### ISSUE THREAD

**Issue by CoinGame** [Daology/Support#3]
Please leave a comment here if you would like to join the Daology.org closed testing period. If you are not accepted immediately please don't fret, we will increase the numbers of users over time.

**Comment by jooize** [comment]
I'd like to join.

**Comment by cryptog** [comment]
I am in!

**Comment by Nagalim** [comment]
I'd like to try.

**Comment by CoinGame** [comment]
@jooize @cryptog @Nagalim You've all been granted access. Please try to login. Let us know if you have any questions. If you find any issues you can click the bug icon at the top left to quickly submit a report.
