### ISSUE TITLE
Escaping * fails (\*)

### ISSUE THREAD

**Issue by jooize** [Daology/Support#6]
Markdown:

```
Lists with Markdown in Discourse: *(asterisk (\*) and plus (+) do the same)*
```

Results:
![](https://cloud.githubusercontent.com/assets/719371/11006331/8669fa40-84c3-11e5-9aea-f552c0e7c551.png)

**Comment by CoinGame** [comment]
Why are you adding the starting \* and ending *? are you trying to make all of that text bold? Use two *

`**(asterisk (\*) and plus (+) do the same)**`

**Comment by jooize** [comment]
I'm trying to make it italics.

**Comment by brossi** [comment]
From my testing, escaping works correctly, but it is dependent on the usage. 

The list item construct, `* List test (\*)`, renders correctly. But when used within a block of emphasised text it breaks.

```
*emphasized text with a literal in it (\*) does not*
```

In the second case, you can use the alternate mark for emphasis, `_`:

```
_emphasized text with a literal in it (\*) works_
```

**Comment by jooize** [comment]
Got it, thanks!

**Comment by brossi** [comment]
I'll make sure that this scenario gets added to the Markdown style guide because I'm sure it's one that will occasionally surface. Thank you for asking the question.

**Comment by CoinGame** [comment]
Oh yeah sorry I was aware of the _ _ for italics. Glad it worked out.
